name: package-manager-ci

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  npm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [18, 20]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with npm
        run: pnpm install
      
      - name: Compile with npm
        run: npm run build:code

      - name: Run tests with npm
        run: |
          npm run test
        env:
          NODE_OPTIONS: no-network-family-autoselection
          
  pnpm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [18, 20]
        os: [ubuntu-latest]
        pnpm-version: [8]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}

      - run: pnpm install
      
      - name: Compile with pnpm
        run: pnpm run build:code

      - name: Run tests with pnpm
        run: |
          pnpm run test
        env:
          NODE_OPTIONS: no-network-family-autoselection 

  bun:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Maintenance and active LTS
        bun-version: [latest, canary]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install with bun
        run: bun install
      
      - name: Compile with bun
        run: bun run build:code

      - name: Run tests with pnpm
        run: |
          bun run test
        env:
          NODE_OPTIONS: no-network-family-autoselection 

  yarn:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [18, 20]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          yarn install --ignore-engines

      - run: yarn

      - name: Compile with yarn
        run: yarn run build:code

      - name: Run tests with yarn
        run: |
          yarn run test
        env:
          NODE_OPTIONS: no-network-family-autoselection 
